// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzpuleujwwrqnwqqtbcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6cHVsZXVqd3dycW53cXF0YmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTIzMzAsImV4cCI6MjA2Nzk2ODMzMH0.P_1ac4SJ2iXLci-c61d38Ej1396nmxXPXO7wrspzBM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});