// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iupkalgyljvkwrkeodxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cGthbGd5bGp2a3dya2VvZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTc4OTUsImV4cCI6MjA2NjUzMzg5NX0.wvVCHfwt8zO18SCeKu8N-7OufIIFo2FZIzGcFqLQw20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});